CREATE TABLE EmployeeDetails(
EMP_DETAILS_GUID raw(16) default SYS_GUID(),
EMP_ID       VARCHAR2(15) NOT NULL,
EMP_NAME     VARCHAR2(50) NOT NULL,
EMP_DOB      DATE NOT NULL,
EMP_EMAIL    VARCHAR2(30) NOT NULL,
CONSTRAINT P_KEY_EMP_DETAILS_GUID PRIMARY KEY(EMP_DETAILS_GUID),
CONSTRAINT U_KEY_EMPLOYEE_EMP_ID UNIQUE(EMP_ID),
CONSTRAINT U_KEY_EMPLOYEE_EMAIL UNIQUE(EMP_EMAIL)
);

CREATE TABLE EMPLOYEEROLES(
EMP_ROLE_GUID   raw(16) default SYS_GUID(),
EMP_ROLE     varchar2(15),
CONSTRAINT P_KEY_EMP_ROLE_GUID PRIMARY KEY(EMP_ROLE_GUID),
CONSTRAINT U_KEY_EMP_ROLE UNIQUE(EMP_ROLE)
);

CREATE TABLE EMPLOYEE_ROLES_MAPPING(
EMP_ROLES_MAPPING_GUID   raw(16) default SYS_GUID(),
EMP_ID     VARCHAR2(15) NOT NULL,
EMP_ROLE   VARCHAR2(15) NOT NULL,
CONSTRAINT P_KEY_EMP_ROLE_MAPPING_GUID PRIMARY KEY(EMP_ROLES_MAPPING_GUID),
CONSTRAINT F_KEY_ROLES_MAPPING_EMPID FOREIGN KEY(EMP_ID) REFERENCES EMPLOYEEDETAILS(EMP_ID),
CONSTRAINT F_KEY_ROLES_MAPPING_EMPROLE FOREIGN KEY(EMP_ROLE) REFERENCES EMPLOYEEROLES(EMP_ROLE)
);

create or replace FUNCTION RANDOM_GUID
    RETURN VARCHAR2 IS

    RNG    NUMBER;
    N      BINARY_INTEGER;
    CCS    VARCHAR2 (128);
    XSTR   VARCHAR2 (4000) := NULL;
  BEGIN
    CCS := '0123456789' || 'ABCDEF';
    RNG := 15;

    FOR I IN 1 .. 32 LOOP
      N := TRUNC (RNG * DBMS_RANDOM.VALUE) + 1;
      XSTR := XSTR || SUBSTR (CCS, N, 1);
    END LOOP;

    RETURN SUBSTR(XSTR, 1, 4) || '-' ||
        SUBSTR(XSTR, 5, 4)        || '-' ||
        SUBSTR(XSTR, 9, 4)        || '-' ||
        SUBSTR(XSTR, 13,4)        || '-' ||
        SUBSTR(XSTR, 17,4)        || '-' ||
        SUBSTR(XSTR, 21,4)        || '-' ||
        SUBSTR(XSTR, 24,4)        || '-' ||
        SUBSTR(XSTR, 28,4);
END RANDOM_GUID;

DROP TABLE EMPLOYEEDETAILS;
DROP TABLE EMPLOYEEROLES;

INSERT INTO EMPLOYEEDETAILS(EMP_ID, EMP_NAME, EMP_DOB, EMP_EMAIL) values ('885797', 'Harsh Vardhan Sharma', TO_DATE('20-01-1992','dd-mm-yyyy'), 'hvsharma@live.in');
INSERT INTO EMPLOYEEDETAILS(EMP_ID, EMP_NAME, EMP_DOB, EMP_EMAIL) values ('457013', 'Subbu Mopuri', TO_DATE('11-12-1985','dd-mm-yyyy'), 'subbu@xerox.com');

select * from EMPLOYEEDETAILS;